##Supabase Transaction Pooler (port 6543)
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.uffhlonjebmxvxzmbgok
spring.datasource.password=adminunivibe123

##Driver
spring.datasource.driver-class-name=org.postgresql.Driver

##HikariCP tuning
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5
spring.datasource.hikari.minimumIdle=2
spring.datasource.hikari.idleTimeout=30000
spring.datasource.hikari.maxLifetime=1800000

spring.datasource.hikari.data-source-properties.prepareThreshold=0

##JPA / Hibernate settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

##Optional: If you get SSL handshake errors (rare but possible)
spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require

spring.security.user.name=admin
spring.security.user.password={noop}admin

spring.config.import=optional:file:.env[.properties]


jwt.secret=${JWT_SECRET:local_dev_fallback_secret}

logging.level.org.springframework.security=DEBUG

# Mail (Yahoo SMTP)
spring.mail.host=smtp.mail.yahoo.com
spring.mail.port=587
spring.mail.username=univibe2025@yahoo.com
spring.mail.password=${MAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8